spring:
  datasource:
    url: jdbc:postgresql://localhost/library
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  flyway:
    locations: classpath:/db/migration/postgresql