server:
  servlet:
    jsp:
      registered: false
  tomcat:
    max-connections: 30
    threads:
      max: 30
    basedir: tomcat
    accesslog:
        enabled: true
        pattern: '%t %a "%r" %s (%D ms)'
  compression:
    enabled: true
    min-response-size: 512
    mime-types: text/html,text/xml,text/plain,text/css,application/json

spring:
  application:
    name: library
  jackson:
    serialization:
      indent_output: true
    deserialization:
      fail-on-unknown-properties: true
  freemarker:
    enabled: true
    cache: true
    suffix: .ftl
  datasource:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 10
      connection-test-query: SELECT 1
      pool-name: library-db-cp
    initialization-mode: never
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
    open-in-view: false
  mvc:
    throw-exception-if-no-handler-found: true
  jmx:
    enabled: false
  flyway:
    locations: classpath:db/migration/h2

library:
  size: 0

logging:
  file:
    name: library.log