spring:
  security:
    user:
      name:
      password:
      roles: ADMIN
  application:
    admin:
      enabled: true

management:
  security:
    role: ADMIN
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  endpoints:
    web:
      base-path: /admin
      exposure:
        include: '*'
  info:
    git:
      mode: full



